### ISSUE TITLE
expanding-cards background image does not adhere to border-radius at large window size

### ISSUE THREAD

**Issue by snimmagadda1** [bradtraversy/50projects50days#5]
Not sure if you wan't issues/PRs on this so feel free to close 😅  Love the course so far! 

I noticed at large window sizes, the background image of the expanding cards moves/doesn't round because the property `background-size: auto 100%` on the class `panel`. 

It could be changed to `background-size: cover` as a quick fix to prevent this behavior (see below)
![Screen Shot 2020-12-01 at 4 34 08 PM](https://user-images.githubusercontent.com/19558427/100799702-7d77ba00-33f3-11eb-9501-dadc0aea9626.png)

![Screen Shot 2020-12-01 at 4 34 14 PM](https://user-images.githubusercontent.com/19558427/100799715-81a3d780-33f3-11eb-9330-6bbd24514f56.png)

**Comment by bradtraversy** [comment]
Fixed, thank you. I will add it to the course as well
