### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by jassehomar** [bradtraversy/50projects50days#6]
Hi Brad,

Congrats on your new course. Wishing you massive sales on your course lunch. 
I wanted to ask what is the License for this project? Since it is made public does it mean that it can be forked and use anyhow?

Thanks in advance.

**Comment by bineetNaidu** [comment]
> Hi Brad,
> 
> Congrats on your new course. Wishing you massive sales on your course lunch.
> I wanted to ask what is the License for this project? Since it is made public does it mean that it can be forked and use anyhow?
> 
> Thanks in advance.

I think Most probably it will be licensed as MIT :thinking: ?

**Comment by bradtraversy** [comment]
Yes, sorry I am adding the MIT license now.

You are free to do what you want with the code, I just ask that it is not sold outright
